export const source = [
    {
        id:0,
        value:"踢",
        animation:"/anime/kickAnime.mp4",
        sound:"/sound/kickSound.mp3"
    },
    {
        id:1,
        value:"足",
        animation:"",
        sound:""
    },
    {
        id:2,
        value:"球",
        animation:"",
        sound:""
    }
]
