export const source = [
    {
        id:0,
        value:"踢",
        animation:"./anime/kickAnime.mp4",
        sound:"./sound/kickSound.mp3"
    },
    {
        id:1,
        value:"足",
        animation:"./anime/footAnime.mp4",
        sound:"./sound/footSound.mp3"
    },
    {
        id:2,
        value:"球",
        animation:"./anime/ballAnime.mp4",
        sound:"./sound/ballSound.mp3"
    }
]
